trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: BuildAndDeploy
    steps:
        - script: |
           echo "Validating PR"
           displayName: 'Run validation'
