trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: PRValidation
    steps:
      - script: |
          echo "Validating PR"
        displayName: 'Run validation'
